# Generated by Django 4.2.3 on 2024-06-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('skills', models.CharField(blank=True, max_length=200)),
                ('contact_details', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
