# Generated by Django 4.2.3 on 2024-06-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_alter_profile_contact_details_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
    ]
